# Generated by Django 3.1.7 on 2021-03-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='choices',
            field=models.CharField(choices=[(1, 'first'), (2, 'second')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
