# Generated by Django 3.1.7 on 2021-03-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_comment_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choices',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second')], max_length=2),
        ),
    ]
