# Generated by Django 3.1.7 on 2021-03-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20210330_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choices',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second')], max_length=3),
        ),
    ]
